name: CI
on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Generate google-services.json
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > $GITHUB_WORKSPACE/app/google-services.json
      - name: build
        run: ./gradlew build
